name: "🐞 Bug (Development)"
description: Bug fix request for software developers
title: "🐞 What should we fix?"
labels: ["t: bug", "o: development"]
projects: ["planifice/1"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please, fill in the fields below. And don't forget to add extra labels if necessary.
  - type: textarea
    attributes:
      label: Description
      description: Describe the bug in detail.
      placeholder: Enter text...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Tell us how to reproduce the bug.
      placeholder: Enter text...
      value: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: Describe the expected behaviour.
      placeholder: Enter text...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional info
      description: |
        Provide links, images, videos — anything related to the issue.
      placeholder: |
        Enter text or attach files by clicking this area and then dragging them in...
    validations:
      required: false
