name: "🎁 Update (Development)"
description: Dependency update request for software developers
title: "🎁 What should we update?"
labels: ["t: update", "o: development"]
projects: ["planifice/1"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please, fill in the fields below. And don't forget to add extra labels if necessary.
  - type: textarea
    attributes:
      label: Description
      description: Specify the name and the target version of the dependency to be updated.
      placeholder: Enter text...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reasoning
      description: Tell us why the dependency update is needed.
      placeholder: Enter text...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional info
      description: |
        Provide links, images, videos — anything related to the issue.
      placeholder: |
        Enter text or attach files by clicking this area and then dragging them in...
    validations:
      required: false
